# Fichier .streamlit/secrets.toml
SUPABASE_URL = "https://icjcseqyhlymfqcchlyl.supabase.co"
SUPABASE_KEY = "sb_publishable_528qPZh4CGs5aHAtk9tTzA_NWVtUOA9"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465
SMTP_EMAIL = "eric.kuter@gouv.nc"  # ou l'email applicatif IDENTIS
SMTP_PASSWORD = "pwii zybt wqgp nmep"